# Generated by Django 3.1 on 2020-08-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-commment_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='commment_date',
        ),
    ]
